runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "1d"

handlers:

- url: /(.+)
  static_files: public/\1
  upload: public/(.*)

- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /img
  static_dir: img


libraries:
- name: webapp2
  version: "2.5.2"

skip_files:
  # - ^(.*/)?app\.yaml
  # - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^fabfile\.py
  - ^testrunner\.py
  - ^grunt\.js
  - ^node_modules/(.*/)?